### ISSUE TITLE
Design resource page and navigation

### ISSUE THREAD

**Issue by krumware** [CovidSC/covidsc-web#10]
We need to move the resource links to a page that is accessed using the Find Resources button.
This page should categorize and list resources, and allow for a very brief (one or two lines on mobile) explanation of the resource.
A user should also be able to easily navigate back to the homepage. (side question, should COVID SC in the header bar be a link?)

**Comment by kbakeann** [comment]
https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e8222bb120af47227babca6/
![Resources](https://user-images.githubusercontent.com/33105088/77942936-65f79880-728a-11ea-93d8-aa5bbae8c7b8.png)

https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e8222bcf6f7726cf13a8512/
![Resources](https://user-images.githubusercontent.com/33105088/77942952-6d1ea680-728a-11ea-8ab7-edc2bd5311a5.png)

https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e8222be0077f714c16d4b26/
![Resources widescreen](https://user-images.githubusercontent.com/33105088/77942954-6e4fd380-728a-11ea-9067-9a0bcc1b475e.png)
