### ISSUE TITLE
Mandates/Curfews section

### ISSUE THREAD

**Issue by kbakeann** [CovidSC/covidsc-web#14]
We would like to add a section that informs users of any mandates and curfews that have been placed in their area. This may either be state-wide or county specific, I'll have to look further into it to be sure. 
I think this will be a great addition and will benefit our users greatly, keeping them up-to-date on what they need to do to stay safe. 

I think this section will most likely go directly below the "Get Help" section as this will hold very important information

**Comment by jackneil** [comment]
Nice. That could be great ... especially if we tie a request to 'know the user's location' to a filtered page with everything useful for them

**Comment by kbakeann** [comment]
After looking into this I believe it will be better for this to be a separate page, as opposed to a section, because of the sheer amount of information that could to be displayed here. I've mocked up what this might look like but I'm not going to push it any further without feedback as the information I have in this mockup is just a suggestion/example and exactly _what_ we want to show could still be up for debate. I included sources for all of my information and tried to make it as digestible as possible.

![Mandates and curfews](https://user-images.githubusercontent.com/33105088/78189453-0fcc5600-7440-11ea-8483-af54a1278930.png)

![Mandates and curfews](https://user-images.githubusercontent.com/33105088/78189438-07741b00-7440-11ea-837c-2325264fba6c.png)

**Comment by krumware** [comment]
I propose that making the whole banner clickable will probably be a usability issue. It isn't clear to a user, and also might be an accidental click. should we explore other ways to launch it?

**Comment by krumware** [comment]
For content, we may consider limiting it to "official gov't sources" only. Linking to news pages and things increases the amount of curation we need to do, also might open up a credibility can of worms.

**Comment by kbakeann** [comment]
This is going to be its own separate page.
Users can access this page by going to the "Find Resources" page and then selecting "Mandates and Curfews" or they can select the urgent updates banner on the Homepage. 

https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e8638f2db34aa46515dd022/
![Mandates and curfews](https://user-images.githubusercontent.com/33105088/79158173-de3e7d80-7da3-11ea-9e0c-d382ddf4528b.png)
https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e8638f128b75746e6ce8dcb/
![Mandates and curfews](https://user-images.githubusercontent.com/33105088/79158189-e4345e80-7da3-11ea-9c10-02f07378119e.png)
