### ISSUE TITLE
Update icon assets

### ISSUE THREAD

**Issue by krumware** [CovidSC/covidsc-web#31]
Need to update the icon and launch screen assets in the web manifest.

Assets are located here:
https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e87b75ed23311bc803cca15

**Comment by krumware** [comment]
@ke

**Comment by krumware** [comment]
@kbakeann the asset labeled as 50x50 is actually 72x72 in zeplin

**Comment by kbakeann** [comment]
Fixed!
