### ISSUE TITLE
50x50 icon image asset is actually 72x72

### ISSUE THREAD

**Issue by krumware** [CovidSC/covidsc-web#41]
The image asset for the 50x50 icon is actually 72x72, causing an error in the web app manifest.

![image](https://user-images.githubusercontent.com/17303782/78827927-e799a580-79b1-11ea-86d4-56f22e9ae527.png)

**Comment by kbakeann** [comment]
Oops! Try it now, it should be updated in Zeplin

**Comment by krumware** [comment]
Looks good! ![image](https://user-images.githubusercontent.com/17303782/78833582-1ec08480-79bb-11ea-87dc-09be712ac4e2.png)

**Comment by krumware** [comment]
commented on the wrong issue.
Can you do the same for this image as you did for the favicon? that was super helpful!

**Comment by krumware** [comment]
commented on the wrong issue.
@kbakeann Can you do the same for this image as you did for the favicon? that was super helpful!
