### ISSUE TITLE
Initial design for frontend

### ISSUE THREAD

**Issue by krumware** [CovidSC/covidsc-web#5]
CovidSC.com is meant to be a fast-access "get information, self-triage, and get help" website.
"Go to CovidSC.com to get help"

Link to the current website: https://www.covidsc.com/

Since the content of this page may shift, we need to focus on structure initially.
The current website has the information needed, but is a poor mobile experience.

### Technical reqs

 - This needs to be a mobile-first single page application and downloadable PWA.
 - We DO need to scale to desktop
 - Complexity (clicks / page depth) should be very limited. 

### Ideal experience flow

Land on application and get information -> take action (report symptoms/lack of symptoms) OR access resources.

### Non-functional items

 - Information should be replaceable if another state wants to substitute content (own stats, own resources, own contact info)

### Functional items needed

 - Current SC covid counts.
   - total cases vs deaths
   - daily change (delta) for total cases vs deaths
 - Current national covid counts.
   - total cases vs deaths
   - daily change (delta) for total cases vs deaths
 - Visual aides
   - Map of SC with stats (can remain unchanged / styling limited)
   - Chart depicting SC covid counts over time (this may be enhanced later)
 - Symptom reporting
   - currently this is an external link
   - This may evolve into a container for an Orbita self-triage and reporting chatbot [Orbita Covid chatbot](https://go.orbita.ai/orbita-launches-screening-chatbot-covid19-patient-education-triage-virtual-navigation?utm_campaign=%5BALL%20SOLUTIONS%20-%20Orbita%20COVID-19%5D%20March%202020%20-%20present&utm_source=homepageannouncementbar&utm_content=covid19landingpage)
 - Link to DHEC's Covid page
 - List of additional resources or "Get Help" link to resources page
   - (currently contents is limited and seen as "EMPLOYEE needing help", etc)
 - Information about the application
   - sponsors (currently Hank AI and Krumware, as seen in footer)
   - current application version

### Potential pages / site map

 - Information page (landing)
 - Symptom reporting (currently external link)
 - "Get Help" resources page

### Branding

 - SC state colors need to be used
 - State flag is currently being used for app icon. We would to remain understated and focused. additional branding may come if time allows.

**Comment by krumware** [comment]
@jackneil anything missing/wrong here?

**Comment by krumware** [comment]
@jackneil can you invite `thedanmarino` and `kbakeann`?

**Comment by jackneil** [comment]
done

Jack Neil
CEO / Hank AI, Inc.
jack.neil@hank.ai
(w) +1.904.GET.HANK
(m) +1.803.466.7551

Sent via Superhuman ( https://sprh.mn/?vip=jack.neil@hank.ai )

**Comment by jackneil** [comment]
Looks good. I'd add that we can overlay the symptom reporting as pulled from covidnearyou.org. I've already updated the script on index.html to do this and overlay it on the map.

**Comment by kbakeann** [comment]
Colin and I are currently running through the site map and establishing a workflow for this. Will update with wireframes/process work shortly

**Comment by kbakeann** [comment]
Dev. issues for the Homepage and resources page have been created

Homepage #61 
Resources #63 

Closing this epic
