### ISSUE TITLE
[Homepage]: Build Homepage

### ISSUE THREAD

**Issue by kbakeann** [CovidSC/covidsc-web#61]
# Feature request

## Feature type (Frontend / Backend / Other)
Frontend

## Desired Functionality
Implement designs for the homepage. This includes four sections: Get Help/buttons, Cases/deaths cards, Map, Table

320px
https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e8222bb78c56a1630d2f56c/
![Homepage](https://user-images.githubusercontent.com/33105088/77943394-24b3b880-728b-11ea-81c4-1a252790693d.png)

624px
https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e8222bf120af47227babcc9/
![Homepage](https://user-images.githubusercontent.com/33105088/77943334-0e0d6180-728b-11ea-8a76-b12b38351027.png)

800px+
https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e8222bfbde8ee6e79703796/
![Homepage widescreen](https://user-images.githubusercontent.com/33105088/77943339-0fd72500-728b-11ea-9ef0-7f3eb87a8ddb.png)

## Other remarks
Design issue: https://github.com/CovidSC/covidsc-web/issues/11

**Comment by krumware** [comment]
Already complete
