### ISSUE TITLE
[Homepage]: Add graph

### ISSUE THREAD

**Issue by kbakeann** [CovidSC/covidsc-web#62]
# Feature request

## Feature type (Frontend / Backend / Other)
frontend/backend

## Desired Functionality
Add graph that shows the number of cases per county over time. 
We can show the number of cases in SC over time as a constant, and be able to select which SC county to compare that with. 

We should _only_ show South Carolina counties here to keep the data focused and easily digestible.

https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e8222bb78c56a1630d2f56c/
![Homepage](https://user-images.githubusercontent.com/33105088/78159902-36bf6380-7411-11ea-91d9-5495c24321aa.png)

https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e8222bf120af47227babcc9/
![Homepage](https://user-images.githubusercontent.com/33105088/78159964-4c348d80-7411-11ea-80a3-7951e8ca00c7.png)

### Dropdown menu
Dropdown menu height = 288px
Min-width = 288px
Max-width = 392px
https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e94b5cd9be6bd79c045ddca/
![Dropdown](https://user-images.githubusercontent.com/33105088/79150790-5a7e9400-7d97-11ea-9927-c91311747ae6.png)
https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e94b5d0dfa2157a54375056/
![Dropdown](https://user-images.githubusercontent.com/33105088/79150813-623e3880-7d97-11ea-9085-47da8893c6fb.png)

## Other remarks
Design issue: https://github.com/CovidSC/covidsc-web/issues/16

**Comment by krumware** [comment]
assigning to Colby since he's already on #23
